
//#region useractions 
export const SET_USER = "SET_USER";
export const LOG_OUT = "LOG_OUT";
export const ADD_USER = "ADD_USER";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const ADD_CREDIT_LIMIT = "ADD_CREDIT_LIMIT";
export const ADD_CREDIT_ERROR = "ADD_CREDIT_ERROR";
export const GET_USERS_ERROR = "GET_USERS_ERROR";
export const GET_USERS_PENDING = "GET_USERS_PENDING";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
//#endregion useractions


//#region creditapproval
export const GET_CREDITAPPROVALS_SUCCESS = "GET_CREDITAPPROVALS_SUCCESS";
export const GET_CREDITAPPROVALS_ERROR = "GET_CREDITAPPROVALS_ERROR";
export const GET_CREDITAPPROVALS_PENDING = "GET_CREDITAPPROVALS_PENDING";
//#endregion

//#region order
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_ERROR = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_PENDING = "GET_ORDERS_PENDING";
export const GET_ORDERS_PENDING_SUCCESS = "GET_ORDERS_PENDING_SUCCESS";
//#endregion

//#region PAYMENT
export const GET_PAYMENTS_SUCCESS = "GET_PAYMENTS_SUCCESS";
export const GET_PAYMENTS_ERROR = "GET_PAYMENTS_SUCCESS";
export const GET_PAYMENTS_PENDING = "GET_PAYMENTS_PENDING";
//#endregion

//#region article
export const GET_ARTICLES_SUCCESS = "GET_ARTICLES_SUCCESS";
export const GET_ARTICLES_ERROR = "GET_ARTICLES_ERROR";
export const GET_ARTICLES_PENDING = "GET_ARTICLES_PENDING";
//#endregion

//#region admin management
export const GET_ALLADMIN_SUCCESS = "GET_ALLADMIN_SUCCESS";
export const GET_ALLADMIN_PENDING = "GET_ALLADMIN_PENDING";
export const GET_ALLADMIN_ERROR = "GET_ALLADMIN_ERROR";
export const ADD_ADMIN_SUCCESS = "ADD_ADMIN_SUCCESS";
export const ADD_ADMIN_ERROR = "ADD_ADMIN_ERROR";
export const ADD_ADMIN_PENDING = "ADD_ADMIN_PENDING";
export const GET_ADMIN_ROLE = "GET_ADMIN_ROLE";
export const ADD_ADMIN_ROLE = "ADD_ADMIN_ROLE";
//#endrgion
